FROM ubuntu:22.04

ENV DEBIAN_FRONTEND noninteractive
ENV DISPLAY=:1

RUN apt-get update && \
    apt-get install -y \
        xserver-xorg \
        novnc \
        tivervnc-common \
        tigervnc-standalone-server \
        websockify \
        x11-apps

RUN vncserver :1 -geometry 800x600 -depth 24
RUN websockify -D --web=/usr/share/novnc 80 localhost:5901

CMD ["xeyes"]
