FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  libdbus-1-3 \
  libfontconfig1 \
  libgl1-mesa-dev \
  libglib2.0-0 \
  libxkbcommon-x11-0 \
  libxcb-icccm4 \
  libxcb-image0 \
  libxcb-keysyms1 \
  libxcb-randr0 \
  libxcb-render-util0 \
  libxcb-shape0 \
  python3.10 \
  python3-pip && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

ARG DLC_VERSION

RUN pip install --no-cache-dir deeplabcut[gui,tf]==${DLC_VERSION} && \
  pip uninstall -y opencv-python opencv-python-headless && \
  pip install --no-cache-dir opencv-python-headless

CMD ["python3", "-m", "deeplabcut"]

