apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test
spec:
  selector:
    matchLabels:
      app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: test:test
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: python
