FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    python3.10 \
    python3-pip \
    libglib2.0-0 \
    libgl1-mesa-dev \
    libdbus-1-3 \
    libfontconfig1 \
    libxkbcommon-x11-0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-shape0 && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir deeplabcut[gui,tf]==2.3.0 && \
    pip uninstall -y opencv-python opencv-python-headless && \
    pip install --no-cache-dir opencv-python-headless

RUN apt-get update
RUN apt-get install -y libqt6pdf6
RUN apt-get install -y libfontconfig1 libxrender1 libxi6 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
RUN apt-get install -y xfce4
RUN apt-get install -y ffmpeg

RUN pip install --no-cache-dir -U napari[all]

CMD ["python3", "-m", "deeplabcut"]
