
FROM nvidia/cuda:11.7.0-cudnn8-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -yy \
    && apt-get install -yy --no-install-recommends python3 python3-pip python3-dev ffmpeg libsm6 libxext6 \
    libgtk-3-dev python3-wxgtk4.0 locales \
    && apt-get install -yy --no-install-recommends build-essential make cmake gcc g++ \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && locale-gen en_US.UTF-8 en_GB.UTF-8

RUN pip3 install --no-cache-dir --upgrade pip \
 && pip3 install --no-cache-dir --upgrade "deeplabcut[gui]<2.3" numpy==1.20.3 decorator==4.4.2 tensorflow==2.5.0 \
 && pip3 list \
 && pip3 uninstall --yes tensorboard \
 && pip3 install --no-cache-dir --upgrade protobuf==3.20.1

# TODO required to fix permission errors when running the container with limited permission.
RUN chmod a+rwx -R /usr/local/lib/python3.8/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained

RUN apt-get update
RUN apt-get install -y dbus-x11

ENV DLClight=False

WORKDIR /project

CMD ["python3", "-m", "deeplabcut"]
