services:
  deeplabcut:
    image: deeplabcut:2.3.0
    build:
      context: ./2.3.0
      dockerfile: Containerfile
    volumes:
      - ${WIN_HOME}/Videos:/root/Desktop
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
    environment:
      - DISPLAY=novnc:0
    depends_on:
      - novnc
    networks:
      - x11

  novnc:
    build:
      context: ./novnc
      dockerfile: Containerfile
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    ports:
      - "8088:8088"
    networks:
      - x11

networks:
  x11:
